extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_f3dlite_material_lights;
extern Lights1 bob_dl_f3dlite_material_001_lights;
extern u8 bob_dl_TextureGround_ci4[];
extern u8 bob_dl_TextureGround_pal_rgba16[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[46];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[4];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
